// Search by id
export const course = {
	"id": "000001-1-2020",
	"year": 2020,
	"active": "Y",
	"level": 1,
	"feeBand": "AUC-STD",
	"crseId": "000001",
	"crseOfferNbr": 1,
	"effdt": "2020-01-01",
	"effdtOffer": "2020-01-01",
	"acadCareer": "UC01",
	"acadGroup": "1200",
	"acadOrg": "HUMANITIES",
	"subject": "ANCHIST",
	"catalogNbr": "100",
	"titleLong": "Ancient Egyptian History",
	"title": "Ancient Egyptian History",
	"description": "A broad overview of ancient Egyptian society and history. It encompasses the approximately 2000 years between the early period of formation of the state of Egypt and the end of the New Kingdom. A focus on political history forms the framework for discussions of the art, literature, and religion of the period.",
	"catalogPrint": "Y",
	"componentPrimary": "LEC",
	"gradingBasis": "GRD",
	"rqrmntGroup": " ",
	"splitOwner": "N",
	"unitsAcadProg": 15,
	"ssrComponent": "LEC",
	"mainProgram": "BA",
	"effStatus": "A"
}

// Filter by
export const courses = {
	"data": [
		{
		"id": "000001-1-2020",
		"year": 2020,
		"active": "Y",
		"level": 1,
		"feeBand": "AUC-STD",
		"crseId": "000001",
		"crseOfferNbr": 1,
		"effdt": "2020-01-01",
		"effdtOffer": "2020-01-01",
		"acadCareer": "UC01",
		"acadGroup": "1200",
		"acadOrg": "HUMANITIES",
		"subject": "ANCHIST",
		"catalogNbr": "100",
		"titleLong": "Ancient Egyptian History",
		"title": "Ancient Egyptian History",
		"description": "A broad overview of ancient Egyptian society and history. It encompasses the approximately 2000 years between the early period of formation of the state of Egypt and the end of the New Kingdom. A focus on political history forms the framework for discussions of the art, literature, and religion of the period.",
		"catalogPrint": "Y",
		"componentPrimary": "LEC",
		"gradingBasis": "GRD",
		"rqrmntGroup": " ",
		"splitOwner": "N",
		"unitsAcadProg": 15,
		"ssrComponent": "LEC",
		"mainProgram": "BA",
		"effStatus": "A"
		},
		{
		"id": "000002-1-2020",
		"year": 2020,
		"active": "Y",
		"level": 1,
		"feeBand": "AUC-STD",
		"crseId": "000002",
		"crseOfferNbr": 1,
		"effdt": "2020-01-01",
		"effdtOffer": "2020-01-01",
		"acadCareer": "UC01",
		"acadGroup": "1200",
		"acadOrg": "HUMANITIES",
		"subject": "ANCHIST",
		"catalogNbr": "102",
		"titleLong": "Ancient Greek History",
		"title": "Ancient Greek History",
		"description": "An introduction to Greek history and civilisation from the Bronze Age to the death of Alexander the Great utilising both archaeological evidence and literary sources.",
		"catalogPrint": "Y",
		"componentPrimary": "LEC",
		"gradingBasis": "GRD",
		"rqrmntGroup": " ",
		"splitOwner": "N",
		"unitsAcadProg": 15,
		"ssrComponent": "LEC",
		"mainProgram": "BA",
		"effStatus": "A"
		},
		{
		"id": "000003-1-2020",
		"year": 2020,
		"active": "Y",
		"level": 1,
		"feeBand": "AUC-STD",
		"crseId": "000003",
		"crseOfferNbr": 1,
		"effdt": "2020-01-01",
		"effdtOffer": "2020-01-01",
		"acadCareer": "UC01",
		"acadGroup": "1200",
		"acadOrg": "HUMANITIES",
		"subject": "ANCHIST",
		"catalogNbr": "103",
		"titleLong": "Roman History",
		"title": "Roman History",
		"description": "An introduction to the civilisation and history of Ancient Rome, with particular reference to the Republic and Early Empire.",
		"catalogPrint": "Y",
		"componentPrimary": "LEC",
		"gradingBasis": "GRD",
		"rqrmntGroup": " ",
		"splitOwner": "N",
		"unitsAcadProg": 15,
		"ssrComponent": "LEC",
		"mainProgram": "BA",
		"effStatus": "A"
		},
		{
		"id": "000004-1-2020",
		"year": 2020,
		"active": "Y",
		"level": 2,
		"feeBand": "AUC-STD",
		"crseId": "000004",
		"crseOfferNbr": 1,
		"effdt": "2020-01-01",
		"effdtOffer": "2020-01-01",
		"acadCareer": "UC01",
		"acadGroup": "1200",
		"acadOrg": "HUMANITIES",
		"subject": "ANCHIST",
		"catalogNbr": "200",
		"titleLong": "Egypt in Dynasty XVIII",
		"title": "Egypt in Dynasty XVIII",
		"description": "The cosmopolitan nature of ancient Egypt during the era of its imperial expansion and its consciousness as a world power. Topics covered include the social, political, and economic ramifications of this sudden change in Egypt's role in the ancient world. The emergence of new religious directions will also be discussed, among which are the state cults of Amun-Re and the religious monotheism of Akhenaton.",
		"catalogPrint": "Y",
		"componentPrimary": "LEC",
		"gradingBasis": "GRD",
		"rqrmntGroup": "900001",
		"rqrmntDescr": "Prerequisite: 15 points at Stage I in Ancient History or Classical Studies, and 30 points passed\nRestriction: ANCHIST 300",
		"splitOwner": "N",
		"unitsAcadProg": 15,
		"ssrComponent": "LEC",
		"mainProgram": "BA",
		"effStatus": "A"
		},
		{
		"id": "000006-1-2020",
		"year": 2020,
		"active": "Y",
		"level": 2,
		"feeBand": "AUC-STD",
		"crseId": "000006",
		"crseOfferNbr": 1,
		"effdt": "2020-01-01",
		"effdtOffer": "2020-01-01",
		"acadCareer": "UC01",
		"acadGroup": "1200",
		"acadOrg": "HUMANITIES",
		"subject": "ANCHIST",
		"catalogNbr": "202",
		"titleLong": "Greece and Persia",
		"title": "Greece and Persia",
		"description": "A study of the contacts and conflicts between Greece and Persia 560-323BC.",
		"catalogPrint": "Y",
		"componentPrimary": "LEC",
		"gradingBasis": "GRD",
		"rqrmntGroup": "900003",
		"rqrmntDescr": "Prerequisite: 15 points at Stage I in Ancient History or Classical Studies, and 30 points passed\nRestriction: ANCHIST 302",
		"splitOwner": "N",
		"unitsAcadProg": 15,
		"ssrComponent": "LEC",
		"mainProgram": "BA",
		"effStatus": "A"
		},
		{
		"id": "000009-1-2020",
		"year": 2020,
		"active": "Y",
		"level": 2,
		"feeBand": "AUC-STD",
		"crseId": "000009",
		"crseOfferNbr": 1,
		"effdt": "2020-01-01",
		"effdtOffer": "2020-01-01",
		"acadCareer": "UC01",
		"acadGroup": "1200",
		"acadOrg": "HUMANITIES",
		"subject": "ANCHIST",
		"catalogNbr": "210",
		"titleLong": "Egyptian Language 1A",
		"title": "Egyptian Language 1A",
		"description": "A study of the Egyptian language, hieroglyphic writing and selected documents up to Dynasty 18.",
		"catalogPrint": "Y",
		"componentPrimary": "LEC",
		"gradingBasis": "GRD",
		"rqrmntGroup": "900005",
		"rqrmntDescr": "Prerequisite: 15 points at Stage I in Ancient History or Classical Studies and 30 points passed",
		"splitOwner": "N",
		"unitsAcadProg": 15,
		"ssrComponent": "LEC",
		"mainProgram": "BA",
		"effStatus": "A"
		},
		{
		"id": "000015-1-2020",
		"year": 2020,
		"active": "Y",
		"level": 2,
		"feeBand": "AUC-STD",
		"crseId": "000015",
		"crseOfferNbr": 1,
		"effdt": "2020-01-01",
		"effdtOffer": "2020-01-01",
		"acadCareer": "UC01",
		"acadGroup": "1200",
		"acadOrg": "HUMANITIES",
		"subject": "ANCHIST",
		"catalogNbr": "222",
		"titleLong": "Ancient Greek Tyranny",
		"title": "Ancient Greek Tyranny",
		"description": "A study of the lives and achievements of individual tyrants in order to establish the causes and effects of the phenomenon of tyranny, and an evaluation of Greek views of tyranny.",
		"catalogPrint": "Y",
		"componentPrimary": "LEC",
		"gradingBasis": "GRD",
		"rqrmntGroup": "900011",
		"rqrmntDescr": "Prerequisite: 15 points at Stage I in Ancient History or Classical Studies, and 30 points passed\nRestriction: ANCHIST 322",
		"splitOwner": "N",
		"unitsAcadProg": 15,
		"ssrComponent": "LEC",
		"mainProgram": "BA",
		"effStatus": "I"
		},
		{
		"id": "000016-1-2020",
		"year": 2020,
		"active": "Y",
		"level": 2,
		"feeBand": "AUC-STD",
		"crseId": "000016",
		"crseOfferNbr": 1,
		"effdt": "2020-01-01",
		"effdtOffer": "2020-01-01",
		"acadCareer": "UC01",
		"acadGroup": "1200",
		"acadOrg": "HUMANITIES",
		"subject": "ANCHIST",
		"catalogNbr": "230",
		"titleLong": "Egypt in Dynasties XI-XVII",
		"title": "Egypt in Dynasties XI-XVII",
		"description": "Covers the history of Egypt during one major phase of unification, the Middle Kingdom, as well as the First and Second Intermediate Periods. Topics analysed include the rise of imperialism in the south (Nubia), the importance of literature of propaganda as a social bond of loyalty, the conquest of the north by the Asiatic Hyksos, and the new artistic style of portraiture.",
		"catalogPrint": "Y",
		"componentPrimary": "LEC",
		"gradingBasis": "GRD",
		"rqrmntGroup": "900012",
		"rqrmntDescr": "Prerequisite: 15 points at Stage I in Ancient History or Classical Studies, and 30 points passed\nRestriction: ANCHIST 330",
		"splitOwner": "N",
		"unitsAcadProg": 15,
		"ssrComponent": "LEC",
		"mainProgram": "BA",
		"effStatus": "A"
		},
		{
		"id": "000017-1-2020",
		"year": 2020,
		"active": "Y",
		"level": 3,
		"feeBand": "AUC-STD",
		"crseId": "000017",
		"crseOfferNbr": 1,
		"effdt": "2020-01-01",
		"effdtOffer": "2020-01-01",
		"acadCareer": "UC01",
		"acadGroup": "1200",
		"acadOrg": "HUMANITIES",
		"subject": "ANCHIST",
		"catalogNbr": "300",
		"titleLong": "Egypt in Dynasty XVIII",
		"title": "Egypt in Dynasty XVIII",
		"description": "The cosmopolitan nature of ancient Egypt during the era of its imperial expansion and its consciousness as a world power. Topics covered include the social, political and economic ramifications of this sudden change in Egypt's role in the ancient world. The emergence of new religious directions will also be discussed, among which are the state cults of Amun-Re and the religious monotheism of Akhenaton.",
		"catalogPrint": "Y",
		"componentPrimary": "LEC",
		"gradingBasis": "GRD",
		"rqrmntGroup": "900013",
		"rqrmntDescr": "Prerequisite: 15 points at Stage II in Ancient History, Classical Studies, or Classical Studies and Ancient History\nRestriction: ANCHIST 200",
		"splitOwner": "N",
		"unitsAcadProg": 15,
		"ssrComponent": "LEC",
		"mainProgram": "BA",
		"effStatus": "A"
		},
		{
		"id": "000019-1-2020",
		"year": 2020,
		"active": "Y",
		"level": 3,
		"feeBand": "AUC-STD",
		"crseId": "000019",
		"crseOfferNbr": 1,
		"effdt": "2020-01-01",
		"effdtOffer": "2020-01-01",
		"acadCareer": "UC01",
		"acadGroup": "1200",
		"acadOrg": "HUMANITIES",
		"subject": "ANCHIST",
		"catalogNbr": "302",
		"titleLong": "Greece and Persia",
		"title": "Greece and Persia",
		"description": "A study of the contacts and conflicts between Greece and Persia 560-323BC.",
		"catalogPrint": "Y",
		"componentPrimary": "LEC",
		"gradingBasis": "GRD",
		"rqrmntGroup": "900015",
		"rqrmntDescr": "Prerequisite: 15 points at Stage II in Ancient History, Classical Studies, or Classical Studies and Ancient History, or 30 points at Stage II in Greek\nRestriction: ANCHIST 202",
		"splitOwner": "N",
		"unitsAcadProg": 15,
		"ssrComponent": "LEC",
		"mainProgram": "BA",
		"effStatus": "A"
		}
	],
	"total": 8519
	}