export const acadGroupMap = {
	"1000": {
		id: "1000",
		name: "creative",
		title: "Creative Arts and Industries"
	},
	"1200": {
		id: "1200",
		name: "arts",
		title: "School of Arts"
	},
	"1500": {
		id: "1500",
		name: "business",
		title: "Business and Economics"
	},
	"1600": {
		id: "1600",
		name: "engineering",
		title: "Engineering"
	},
	"1750": {
		id: "1750",
		name: "bioengineering",
		title: "Bioengineering Institute"
	},
	"1900": {
		id: "1900",
		name: "law",
		title: "Law"
	},
	"2000": {
		id: "2000",
		name: "medical",
		title: "Medical and Health Sciences"
	},
	"2800": {
		id: "2800",
		name: "liggins",
		title: "Liggins Institute"
	},
	"3170": {
		id: "3170",
		name: "education",
		title: "Education and Social Work"
	},
	"4000": {
		id: "4000",
		name: "science",
		title: "Science"
	},
	"6500": {
		id: "6500",
		name: "continuingEd",
		title: "Centre for Continuing Ed"
	},
	"6505": {
		id: "6505",
		name: "newStart",
		title: "New Start"
	},
	"0001": {
		id: "0001",
		name: "uoa",
		title: "The University of Auckland"
	},
}

export const acadOrgMap = {
	"ACTFIN": "Accounting & Finance",
	"ALLINSTITN": "All University Institutions",
	"ALSL": "App Lang Studies & Linguistics",
	"ANTHRO": "Anthropology",
	"ARCHPLAN": "Architecture & Planning",
	"ARTFAC": "Arts",
	"ARTHIS": "Art History",
	"ASIL&L": "Asian Studies",
	"BIOENGINST": "Bioengineering Institute",
	"BUSEC": "Business & Economics",
	"CAI": "Creative Arts & Industries",
	"CCE": "Centre for Cont Education",
	"CHEM": "Chemical Sciences",
	"CHEMAT": "Chemical & Materials Engineeri",
	"CHSSWK": "Counselling, HumServ & SocWork",
	"CIVENV": "Civil & Environmental Engineer",
	"CLAANC": "Classics & Ancient History",
	"CLEAR": "Centre for Lrn & Rsh Higher Ed",
	"CNZAR": "Centre for NZ Art Res & Discov",
	"COMLAW": "Commercial Law",
	"COMSCI": "Computer Science",
	"CRSTIE": "Critical Studies in Education",
	"CSLANGLING": "Cultures, Languages & Linguist",
	"CURRPD": "Curriculum and Pedagogy",
	"DANCE": "Dance Studies Programme",
	"DEVST": "Development Studies",
	"ECE": "Electrical & Computer Engineer",
	"ECON": "Economics",
	"EDADMN": "Faculty Admin Education",
	"EDUCATION": "Education",
	"EDUFAC": "Education & Social Work",
	"ENGFAC": "Engineering",
	"ENGL": "English Drama &Writing Studies",
	"ENGSCI": "Engineering Science",
	"ENV": "Environment",
	"ENVSCI": "Environmental Sci Dept",
	"EULALT": "European Languages & Literatu",
	"EXTERNAL": "External",
	"FINART": "Fine Arts",
	"FSTDCERT": "StudyGroup Foundation Studies",
	"FTV&M": "Media and Communication",
	"GSE": "Graduate School of Management",
	"GSMMAIBUS": "GSM – Māori Business",
	"GSMMASPRO": "GSM - Masters Programmes",
	"GSMMBAPRO": "GSM - MBA Programmes",
	"HIST": "History",
	"HUMANITIES": "Humanities",
	"INTERNATIO": "International",
	"IRESGEN": "Inst for Research on Gender",
	"ISOM": "Info Systems & Operations Mgmt",
	"JHMRC": "James Henare Maori Research",
	"LAWDEP": "Law",
	"LAWFAC": "Law",
	"LEIGH": "Marine Science",
	"LIGGINS": "Liggins Institute",
	"LRNDVP": "Learning Dev and Prof Practice",
	"M&IB": "Management & Intl Business",
	"MAOPACSTD": "Māori and Pacific Studies",
	"MAORI": "Maori",
	"MAORIHLTH": "Te Kupenga Hauora Maori",
	"MAOSTU": "Māori Studies",
	"MATHS": "Mathematics",
	"MECENG": "Mechanical Engineering",
	"MEDADMIN": "Faculty Administration FMHS",
	"MEDFAC": "Medical & Health Sciences",
	"MEDSCI": "Medical Sciences",
	"MRKTNG": "Marketing",
	"MUSIC": "Music",
	"NEWSTART": "New Start",
	"NURSING": "Nursing",
	"NZASIN": "NZ - Asia Institute",
	"OLDARTS": "Outdated Arts Acad Orgs",
	"OLDBUS": "Outdated B&E Acad Orgs",
	"OLDCAI": "Outdated CAI Acad Orgs",
	"OLDEDUC": "Outdated Education Acad Orgs",
	"OLDENG": "Outdated Engineering Acad Orgs",
	"OLDMED": "Outdated FMHS Acad Orgs",
	"OLDSCI": "Outdated Science Acad Orgs",
	"OPTOM": "Optometry & Vision Science",
	"OTHACSER": "Other Academic Services",
	"OTHERACAD": "Other Academic Activities",
	"OUTDATED": "Outdated Acad Orgs",
	"PACSTU": "Pacific Studies",
	"PHARMACY": "Pharmacy",
	"PHIL": "Philosophy",
	"PHYSICS": "Physics",
	"POLSTU": "Politics & Intl Relations",
	"POPHLTH": "Population Health",
	"PROPTY": "Property",
	"PSYCHOL": "Psychology",
	"SBS": "Biological Sciences",
	"SCHMED": "Medicine",
	"SCIFAC": "Science",
	"SLC": "Student Learning Centre",
	"SOCIOL": "Sociology",
	"SOCSCI": "Social Sciences",
	"SPORTS": "Exercise Sciences",
	"STATS": "Statistics",
	"TEAMSOL": "Faculty Business Unit",
	"TEPUNA": "Te Puna Wananga",
	"TFC": "Tertiary Foundation Certificat",
	"THEOL": "Theology",
	"UNKNOWN": "Unknown Department",
	"UOFAK": "The University of Auckland"
}

export const componentCodesMap = {
	"CLN": "Clinic",
	"WRK": "Workshop",
	"FLD": "Field Studies",
	"IND": "Independent Study",
	"LAB": "Laboratory",
	"LEC": "Lecture",
	"ONL": "Online",
	"DIS": "Discussion",
	"TUT": "Tutorial",
	"THE": "Thesis Research",
	"SUP": "Supervision",
	"STU": "Studio",
	"SEM": "Seminar",
	"PRA": "Practicum",
	"RSC": "Research",
	"TBL": "Team Based Learning",
	"PRE": "Prior Study",
	"PLC": "Plenary lecture",
	"ORL": "Oral or Conversation"
}